import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import Layout from '../components/Layout.jsx';
import { ArrowLeft, Calendar, User, Brain } from 'lucide-react';

const getToken = () => localStorage.getItem('token');

function ReportDetailPage() {
    const { reportId } = useParams();
    const navigate = useNavigate();
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchReport();
    }, [reportId]);

    const fetchReport = async () => {
        const token = getToken();
        try {
            const config = { headers: { Authorization: `Bearer ${token}` } };
            const response = await axios.get(`http://localhost:5001/api/reports/${reportId}`, config);
            setReport(response.data);
        } catch (error) {
            console.error('Error fetching report:', error);
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <Layout title="Loading Report...">
                <div className="flex items-center justify-center h-64">
                    <div className="text-center">
                        <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mb-4"></div>
                        <p className="text-gray-500 dark:text-slate-400">Loading report...</p>
                    </div>
                </div>
            </Layout>
        );
    }

    if (!report) {
        return (
            <Layout title="Report Not Found">
                <div className="text-center py-12">
                    <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Report not found</h2>
                    <button
                        onClick={() => navigate(-1)}
                        className="mt-4 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                    >
                        Go Back
                    </button>
                </div>
            </Layout>
        );
    }

    return (
        <Layout title={`${report.projectName} - Report`}>
            <div className="space-y-6">
                {/* Header */}
                <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 p-6">
                    <div className="flex justify-between items-start mb-4">
                        <div>
                            <h1 className="text-3xl font-bold text-gray-800 dark:text-white">{report.projectName}</h1>
                            <p className="text-gray-600 dark:text-slate-400 mt-2 text-lg">
                                {report.reportType} Report
                            </p>
                        </div>
                        <button
                            onClick={() => navigate(-1)}
                            className="flex items-center gap-2 px-4 py-2 bg-gray-200 dark:bg-slate-700 text-gray-700 dark:text-slate-200 rounded-lg hover:bg-gray-300 dark:hover:bg-slate-600 transition-colors"
                        >
                            <ArrowLeft className="w-4 h-4" />
                            Back
                        </button>
                    </div>
                    
                    <div className="border-t border-gray-200 dark:border-slate-700 pt-4 mt-4">
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                            <div className="flex items-center gap-2">
                                <User className="w-4 h-4 text-gray-400" />
                                <div>
                                    <p className="text-gray-500 dark:text-slate-400">Generated By</p>
                                    <p className="font-semibold text-gray-800 dark:text-white">{report.generatedBy}</p>
                                </div>
                            </div>
                            <div className="flex items-center gap-2">
                                <Calendar className="w-4 h-4 text-gray-400" />
                                <div>
                                    <p className="text-gray-500 dark:text-slate-400">Date</p>
                                    <p className="font-semibold text-gray-800 dark:text-white">
                                        {new Date(report.createdAt).toLocaleDateString()}
                                    </p>
                                </div>
                            </div>
                            <div className="flex items-center gap-2">
                                <Brain className="w-4 h-4 text-gray-400" />
                                <div>
                                    <p className="text-gray-500 dark:text-slate-400">AI Model</p>
                                    <p className="font-semibold text-gray-800 dark:text-white text-xs">{report.aiModel}</p>
                                </div>
                            </div>
                            <div>
                                <p className="text-gray-500 dark:text-slate-400">Report ID</p>
                                <p className="font-semibold text-gray-800 dark:text-white text-xs">{report.reportId.slice(0, 12)}...</p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Report Content - RENDERED AS MARKDOWN */}
                <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 p-8">
                    <div className="prose prose-lg dark:prose-invert max-w-none prose-headings:text-gray-800 dark:prose-headings:text-white prose-p:text-gray-700 dark:prose-p:text-slate-300">
                        <ReactMarkdown>{report.generatedText}</ReactMarkdown>
                    </div>
                </div>

                {/* Data Snapshot */}
                <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 p-6">
                    <h2 className="text-xl font-bold mb-4 text-gray-800 dark:text-white">Project Statistics</h2>
                    <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                        <div className="border border-gray-200 dark:border-slate-700 rounded-lg p-4">
                            <p className="text-gray-500 dark:text-slate-400 text-sm">Total Milestones</p>
                            <p className="text-2xl font-bold text-gray-800 dark:text-white">{report.dataSnapshot.totalMilestones}</p>
                        </div>
                        <div className="border border-gray-200 dark:border-slate-700 rounded-lg p-4">
                            <p className="text-gray-500 dark:text-slate-400 text-sm">Completed</p>
                            <p className="text-2xl font-bold text-green-600">{report.dataSnapshot.completedMilestones}</p>
                        </div>
                        <div className="border border-gray-200 dark:border-slate-700 rounded-lg p-4">
                            <p className="text-gray-500 dark:text-slate-400 text-sm">In Progress</p>
                            <p className="text-2xl font-bold text-yellow-600">{report.dataSnapshot.inProgressMilestones}</p>
                        </div>
                        <div className="border border-gray-200 dark:border-slate-700 rounded-lg p-4">
                            <p className="text-gray-500 dark:text-slate-400 text-sm">Total Photos</p>
                            <p className="text-2xl font-bold text-gray-800 dark:text-white">{report.dataSnapshot.totalPhotos}</p>
                        </div>
                        <div className="border border-gray-200 dark:border-slate-700 rounded-lg p-4">
                            <p className="text-gray-500 dark:text-slate-400 text-sm">AI Analyzed</p>
                            <p className="text-2xl font-bold text-blue-600">{report.dataSnapshot.aiProcessedPhotos}</p>
                        </div>
                        <div className="border border-gray-200 dark:border-slate-700 rounded-lg p-4">
                            <p className="text-gray-500 dark:text-slate-400 text-sm">Total Expenses</p>
                            <p className="text-2xl font-bold text-red-600">₱{report.dataSnapshot.totalExpenses.toLocaleString()}</p>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
}

export default ReportDetailPage;
